### PR TITLE
Upgrade to v10 with Angular 16 support

### PR DESCRIPTION
**Pull request by bjorn-einar-bjartnes-4ss**
Combined the changes I did when upgrading to v14 with the fixes you later did 
https://github.com/rajaramtt/ng7-dynamic-breadcrumb/commit/189191ef0318ebd6875b6880eb0604eff4496a62

https://github.com/rajaramtt/ng7-dynamic-breadcrumb/commit/4b60fd793cdd33ceb495ad5cd7064e2c9a1207c1

Skipped the v9 number in case someone would like to add support for angular 15 in between?

### CODE REVIEW

**Comment by bjorn-einar-bjartnes-4ss** [comment]
image

**Comment by bjorn-einar-bjartnes-4ss** [comment]
image
There are still some issues remaining upgrading it

**Comment by bjorn-einar-bjartnes-4ss** [comment]
Some type issues after upgrading 
image

**Comment by bjorn-einar-bjartnes-4ss** [comment]
Converted to draft, this was harder that expected.

**Comment by rajaramtt** [comment]
@bjorn-einar-bjartnes-4ss  Thanks for the PR contribution, Will check and publish on Weekend!.

**Comment by bjorn-einar-bjartnes-4ss** [comment]
@rajaramtt  unfortunately I wasn't able to make it work, so it is not much of a contribution... ng14 to ng16 was harder than expected. Btw, haven't given up, but taking some time to learn more about this upgrade, there are more issues than with the upgrade from 12 to 14 in my experience so far.

**Comment by vutienhc** [comment]
This library is awesome. It's even better when the update to angular 16 can run. Please do it. Thank you.

**Comment by bjorn-einar-bjartnes-4ss** [comment]
Fairly sure this is not the way to upgrade, will try a new PR with using ng update properly and check in steps.
Opened here https://github.com/rajaramtt/ng7-dynamic-breadcrumb/pull/51

**Pull request closed without merging**
